apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: movie-backend
  namespace: movie-store
spec:
  replicas: 3
  strategy:
    blueGreen:
      activeService: movie-backend
      previewService: movie-backend-preview
      autoPromotionEnabled: false
      prePromotionAnalysis:
        templates:
        - templateName: success-rate-template
  selector:
    matchLabels:
      app: movie-backend
  template:
    metadata:
      labels:
        app: movie-backend
    spec:
      containers:
      - name: backend
        image: YOUR_BACKEND_IMAGE:v2
        ports:
        - containerPort: 8000
