apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: movie-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movie-backend
  template:
    metadata:
      labels:
        app: movie-backend
  strategy:
    canary:
      steps:
        - setWeight: 25
        - pause: { duration: 30s }
        - setWeight: 50
        - pause: { duration: 30s }
        - setWeight: 100
  template:
    spec:
      containers:
        - name: backend
          image: your-dockerhub-user/movie-backend:v2
          ports:
            - containerPort: 8000
