apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: movie-backend
  namespace: movie-store
  labels:
    app.kubernetes.io/instance: movie-store
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movie-backend
  template:
    metadata:
      labels:
        app: movie-backend
    spec:
      containers:
        - name: backend
          image: bsajmera/backend:v5
          ports:
            - containerPort: 8000
  strategy:
    canary:
      steps:
        - setWeight: 25
        - pause: { duration: 30s }
        - setWeight: 50
        - pause: { duration: 30s }
        - setWeight: 100
