apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: movie-frontend
  namespace: movie-store
spec:
  replicas: 3
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: { duration: 300 }
      - analysis:
          templates:
          - templateName: success-rate-template
      - setWeight: 60
      - pause: { duration: 300 }
      - setWeight: 100
  selector:
    matchLabels:
      app: movie-frontend
  template:
    metadata:
      labels:
        app: movie-frontend
    spec:
      containers:
      - name: frontend
        image: YOUR_FRONTEND_IMAGE:v2
        ports:
        - containerPort: 8511
