apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-backend
  namespace: movie-store
  labels:
    app: movie-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-backend
  template:
    metadata:
      labels:
        app: movie-backend
    spec:
      containers:
        - name: backend
          image: bsajmera/backend:v5
          ports:
            - containerPort: 8000
