apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-backend
  namespace: movie-store
  labels:
    app: movie-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-backend
  template:
    metadata:
      labels:
        app: movie-backend
    spec:
      containers:
        - name: backend
          image: bsajmera/backend:v1
          ports:
            - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: movie-backend
  namespace: movie-store
spec:
  selector:
    app: movie-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
