apiVersion: v1
kind: Service
metadata:
  name: movie-backend
  namespace: movie-store
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /matrics
    prometheus.io/port: "8000"
spec:
  selector:
    app: movie-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
