apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-frontend
  labels:
    app: movie-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-frontend
  template:
    metadata:
      labels:
        app: movie-frontend
    spec:
      containers:
        - name: frontend
          image: bsajmera/frontend:v2
          ports:
            - containerPort: 8501
          env:
            - name: BACKEND_URL
              value: "http://movie-backend:8000"
