apiVersion: v1
kind: Service
metadata:
  name: movie-frontend
  namespace: movie-store
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "8511"
spec:
  selector:
    app: movie-frontend
  type: LoadBalancer
  ports:
    - name: http-ui
      protocol: TCP
      port: 80
      targetPort: 8501
    - name: http-metrics
      protocol: TCP
      port: 8511
      targetPort: 8511
