apiVersion: v1
kind: Service
metadata:
  name: movie-frontend
  namespace: movie-store
spec:
  selector:
    app: movie-frontend
  type: LoadBalancer
  ports:
    - name: ui
      protocol: TCP
      port: 80            # External port for UI
      targetPort: 8501    # Internal UI port
    - name: metrics
      protocol: TCP
      port: 8511          # Expose metrics port directly
      targetPort: 8511    # Internal metrics port
