apiVersion: v1
kind: Service
metadata:
  name: movie-frontend
  namespace: movie-store
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "8511"
spec:
  selector:
    app: movie-frontend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501    # Port for the UI
    - protocol: TCP
      port: 8511
      targetPort: 8511    # Port for Prometheus metrics
