apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: movie-store
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-github-username/movie-store-deploy.git
    targetRevision: HEAD
    path: rollout
  destination:
    server: https://kubernetes.default.svc
    namespace: movie-store
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
