apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate-template
  namespace: movie-store
spec:
  metrics:
  - name: success-rate
    interval: 5s
    count: 3
    failureLimit: 1
    provider:
      prometheus:
        address: http://my-prometheus-server.monitoring.svc.cluster.local
        query: |
          sum(rate(http_requests_total{status=~"2.."}[1m])) / sum(rate(http_requests_total[1m])) > 0.9
